### ISSUE TITLE
Terrain Collisions

### ISSUE THREAD

**Issue by Quidam2k** [wrld3d/unity-api#37] opened 2017-10-16 17:13 UTC
Getting the following errors when using a streaming camera at an altitude of 2000, taking in a large section of landscape and buildings. Only happens when Terrain Collisions is checked, is fine with buildings and roads.

Let me know if there's more information I can give you.

[Physics.PhysX] Cooking::cook/createTriangleMesh: user-provided triangle mesh descriptor is invalid!
UnityEngine.GameObject:SetActive(Boolean)
Wrld.Streaming.GameObjectStreamer:SetVisible(String, Boolean) (at Assets/Wrld/Scripts/Streaming/GameObjectStreamer.cs:67)
Wrld.MapGameObjectScene:SetVisibleInternal(String, Boolean) (at Assets/Wrld/Scripts/Streaming/MapGameObjectScene.cs:116)
Wrld.MapGameObjectScene:SetVisible(String, Boolean) (at Assets/Wrld/Scripts/Streaming/MapGameObjectScene.cs:109)
Wrld.NativePluginRunner:Update(Single)
Wrld.NativePluginRunner:Update() (at Assets/Wrld/Scripts/NativePluginRunner.cs:133)
Wrld.ApiImplementation:Update() (at Assets/Wrld/Scripts/ApiImplementation.cs:195)
Wrld.Api:Update() (at Assets/Wrld/API/Api.cs:112)
WrldMap:Update() (at Assets/Wrld/API/WrldMap.cs:162)

[Physics.PhysX] cleaning the mesh failed
UnityEngine.GameObject:SetActive(Boolean)
Wrld.Streaming.GameObjectStreamer:SetVisible(String, Boolean) (at Assets/Wrld/Scripts/Streaming/GameObjectStreamer.cs:67)
Wrld.MapGameObjectScene:SetVisibleInternal(String, Boolean) (at Assets/Wrld/Scripts/Streaming/MapGameObjectScene.cs:116)
Wrld.MapGameObjectScene:SetVisible(String, Boolean) (at Assets/Wrld/Scripts/Streaming/MapGameObjectScene.cs:109)
Wrld.NativePluginRunner:Update(Single)
Wrld.NativePluginRunner:Update() (at Assets/Wrld/Scripts/NativePluginRunner.cs:133)
Wrld.ApiImplementation:Update() (at Assets/Wrld/Scripts/ApiImplementation.cs:195)
Wrld.Api:Update() (at Assets/Wrld/API/Api.cs:112)
WrldMap:Update() (at Assets/Wrld/API/WrldMap.cs:162)

**Comment by malcolm-brown** [comment] 2017-10-17 08:37
Hi Quidam2k, thanks for reporting this.

Could we also get the version of Unity you're running, along with the latitude and longitude of the location you're looking at when this error occurs? This should help us narrow down the problem.

**Comment by Quidam2k** [comment] 2017-10-18 20:35
Unity 2017.2.0f3

latitude = 34.009605f;
longitude = -118.500133f;

**Comment by malcolm-brown** [comment] 2017-10-19 09:03
Thanks, we've successfully reproduced this and will aim to get it fixed for next release.  It looks like there are some invalid triangles in the terrain geometry around this area that the MeshCollider component doesn't like.

**Comment by jonty-dawson** [comment] 2018-04-02 08:37
Still occurring in v0.6 - tentatively on v0.7 bugfix release

**Comment by ghost** [comment] 2020-12-29 09:53
This is fixed in v0.7

**Closed by ghost** 2020-12-29 09:53 UTC
Labels: bug
