### ISSUE TITLE
Unity SDK clean import throwing errors

### ISSUE THREAD

**Issue by clearbrian** [wrld3d/unity-api#4] opened 2017-07-07 12:26 UTC
Hi
I've tried to test the Unity package in two sample apps following instructions on 
https://wrld3d.com/unity/latest/docs/api/
I got the iOS sample working fine so apikeys are ok.
I created new Unity app.
Opened WRLD from Asset Store.
I tried Import from Asset Store web page
It popped up alert to setup key. 
Then showed alert about WRLD - Shadow Distance settings being wrong 
I pressed 'Increase'
then opened Scenes > UnityWorldSpace 
and theres lots of errors
Missing Built In GUI styles - see screenshot.

I read the instructions and noticed it said download then import via Project > Assets.
I created a new clean Unity package
I downloaded the package in Asset Store tab > Downloads.
I didnt press IMPORT button.
Instead I right clicked on Project > Asset > Import Package > custom Package
I found the unitypackage in 
/Users/gbxc/Library/Unity/Asset Store-5.x/WRLD/ScriptingModeling/WRLD Unity SDK.unitypackage
imported it
then opened Scenes > UnityWorldSpace 
and got a different error
InvalidOperationException: Operation is not valid due to the current state of the object
System.Collections.Stack.Pop () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections/Stack.cs:329)
UnityEngine.GUILayoutUtility.EndLayoutGroup () (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:323)
UnityEditor.HostView.EndOffsetArea () (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:190)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:238)
UnityEditor.DockArea.OnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:346)

USING Unity 5.6.1.f1
Mac OS Sierra : 10.12.5 (16F73)
new to unity but have deployed to iOS/Android ok.
WRLD ios sample running fine on iphone.

Error when you press IMPORT in asset store web page
<img width="791" alt="unityscreensnapz246" src="https://user-images.githubusercontent.com/132359/27957705-84730144-6317-11e7-80f4-03b0fcddf481.png">

Error when you manually import unitypackage
<img width="806" alt="unityscreensnapz253" src="https://user-images.githubusercontent.com/132359/27957715-93668f36-6317-11e7-8852-674d2b7010ec.png">

**Comment by tim-jenks** [comment] 2017-07-07 12:40
Thanks @clearbrian - we'll investigate and get back to you as soon as possible

**Comment by Palak1610** [comment] 2017-07-07 13:19
hi,
I created new Unity app and Opened WRLD from Asset Store.
I tried Import from Asset Store web page
It popped up alert to setup key.
Then showed alert about WRLD - Shadow Distance settings being wrong
I pressed 'Increase'
then opened Scenes > UnityWorldSpace
and there is lots of errors
"Failed to load 'Assets/Wrld/Plugins/x86_64/StreamAlpha.dll' with error 'The specified module could not be found.
'.
Wrld.ApiImplementation:.ctor(String, CoordinateSystem, Transform, ConfigParams) (at Assets/Wrld/Scripts/ApiImplementation.cs:38)
Wrld.ApiImplementation:.ctor(String, CoordinateSystem, Transform, ConfigParams) (at Assets/Wrld/Scripts/ApiImplementation.cs:21)
Wrld.Api:.ctor(String, CoordinateSystem, Transform, ConfigParams) (at Assets/Wrld/API/Api.cs:46)
Wrld.Api:Create(String, CoordinateSystem, Transform, ConfigParams) (at Assets/Wrld/API/Api.cs:73)
WrldMap:Awake() (at Assets/Wrld/API/WrldMap.cs:94)"

 see screenshot.
USING Unity 5.5.0.f3

![capture](https://user-images.githubusercontent.com/22251426/27959241-473eddde-6344-11e7-82c4-44885e04f946.PNG)

thanking you,
Palak Godhani

**Comment by tim-jenks** [comment] 2017-07-07 13:49
@Palak1610 - could you please confirm your Unity Build Target is x86_64? the WRLD asset should try to do this automatically for you but something may be amiss.

Also, please make sure that you select all of the package files for inclusion on import.

**Comment by clearbrian** [comment] 2017-07-10 08:39
Appears to be working now. I can confirm I was testing android/ ios so platform may have been the wrong one but Im not 100% sure. I came in after the weekend and rebooted and it worked.

**Comment by Palak1610** [comment] 2017-07-10 08:43
Ok
Let me inform after reboot.

Also I select all of the package file while importing package in unity

**Comment by tim-jenks** [comment] 2017-07-10 08:45
I'm going to close the issue. We are unable to reproduce here. I expect that this is a combination of wrong deployment target / wrong deployment architecture. Please comment and I'll re-open if this still persists.

The WRLD Unity SDK attempts to automatically select the appropriate architecture to avoid this issue, but if people experience this please ensure you're selecting the correct deployment platform & architecture in Unity's build settings

**Closed by tim-jenks** 2017-07-10 08:45 UTC
Labels: question

**Comment by YasserEiessa** [comment] 2018-02-25 08:41
Hi 
I'm facing the same issue; 
I just wanted to see the WRLD Unity SDK .. and when I open the UnityWorld scene, I have the same errors..

Failed to load 'Assets/Wrld/Plugins/x86_64/StreamAlpha.dll' with error 'The specified module could not be found.
![sdk](https://user-images.githubusercontent.com/36810830/36639593-4cc1e036-1a18-11e8-8dc7-626953c546c2.jpg)
