### ISSUE TITLE
Not able to archive IPA when Unity project includes Wrld

### ISSUE THREAD

**Issue by YohanBaillot** [wrld3d/unity-api#27] opened 2017-09-21 03:35 UTC
Hello

I am unable to archive an IPA from Xcode when Wrld is added to a Unity project. The archiving happens fine when Wrld is not included. I am using Unity 2017.2.b11 and Xcode 9.0 beta 4 (9M189t). The IPATool seems to be failing. The logs are attached

[Unity-iPhone_2017-09-20_20-30-04.387.xcdistributionlogs.zip](https://github.com/wrld3d/unity-api/files/1319894/Unity-iPhone_2017-09-20_20-30-04.387.xcdistributionlogs.zip)

**Comment by YohanBaillot** [comment] 2017-09-21 03:37
The logs section that might be useful is hereunder:

 {
            code = 646;
            description = "ipatool failed with an exception: #<NoMethodError: undefined method `toolsPath' for nil:NilClass>\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:804:in `rawLoadCommands'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:820:in `rpaths'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:259:in `resolveLoadedDylibs'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:1415:in `block (2 levels) in initialize'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:1414:in `each'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:1414:in `block in initialize'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:1413:in `each'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:1413:in `initialize'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2278:in `new'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2278:in `ProcessIPA'\n    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'";
            info =             {
            };
            level = ERROR;
            type = exception;
        }

**Comment by johnbell84** [comment] 2017-09-25 07:57
Hi Yohan,

Thanks very much for the issue report and logs.  We actually received and investigated another report of this problem, but unfortunately were not able to reproduce it locally.  

If possible, would you be able to supply us with a copy of a failing project to help us investigate?  If you'd rather not send anything publicly, it might be easier to follow up by e-mailing support@wrld3d.com.

Kind regards,

John

**Comment by jonty-dawson** [comment] 2018-04-02 08:45
See troubleshooting notes to mitigate on #45.
Closing this issue

**Closed by jonty-dawson** 2018-04-02 08:45 UTC
Labels: bug
